/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * ChoiceActionPanel.java
 *
 * Created on 8. September 2007, 12:28
 */
package de.cismet.lagis.wizard.panels;

import org.netbeans.spi.wizard.WizardController;
import org.netbeans.spi.wizard.WizardPanelProvider;

import java.awt.event.ActionListener;

import java.util.Map;

import javax.swing.JComponent;

/**
 * DOCUMENT ME!
 *
 * @author   Sebastian Puhl
 * @version  $Revision$, $Date$
 */
public class ChoiceActionPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton cboChangeKind;
    public javax.swing.JRadioButton cboCreateFlurstueck;
    private javax.swing.ButtonGroup cboGroupActions;
    public javax.swing.JRadioButton cboJoinFlurstueck;
    public javax.swing.JRadioButton cboRenameFlurstueck;
    public javax.swing.JRadioButton cboSetFlurstueckActive;
    public javax.swing.JRadioButton cboSetFlurstueckHistoric;
    public javax.swing.JRadioButton cboSplitFlurstueck;
    public javax.swing.JRadioButton cboSplitJoinFlurstueck;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ChoiceActionPanel.
     */
    public ChoiceActionPanel() {
        initComponents();
        cboGroupActions.add(cboCreateFlurstueck);
        cboGroupActions.add(cboJoinFlurstueck);
        cboGroupActions.add(cboRenameFlurstueck);
        cboGroupActions.add(cboSetFlurstueckHistoric);
        cboGroupActions.add(cboSplitFlurstueck);
        cboGroupActions.add(cboSplitJoinFlurstueck);
        cboGroupActions.add(cboChangeKind);
        cboGroupActions.add(cboSetFlurstueckActive);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public boolean isRadioButtonSelected() {
        return cboCreateFlurstueck.isSelected() || cboJoinFlurstueck.isSelected() || cboRenameFlurstueck.isSelected()
                    || cboSetFlurstueckHistoric.isSelected() || cboSplitFlurstueck.isSelected()
                    || cboSplitJoinFlurstueck.isSelected() || cboChangeKind.isSelected()
                    || cboSetFlurstueckActive.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        cboGroupActions = new javax.swing.ButtonGroup();
        cboCreateFlurstueck = new javax.swing.JRadioButton();
        cboRenameFlurstueck = new javax.swing.JRadioButton();
        cboSetFlurstueckHistoric = new javax.swing.JRadioButton();
        cboSplitFlurstueck = new javax.swing.JRadioButton();
        cboJoinFlurstueck = new javax.swing.JRadioButton();
        cboSplitJoinFlurstueck = new javax.swing.JRadioButton();
        cboChangeKind = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        cboSetFlurstueckActive = new javax.swing.JRadioButton();

        cboCreateFlurstueck.setText("Flurst\u00fcck einpflegen");
        cboCreateFlurstueck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cboCreateFlurstueck.setFocusPainted(false);
        cboCreateFlurstueck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cboCreateFlurstueck.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    cboCreateFlurstueckActionPerformed(evt);
                }
            });

        cboRenameFlurstueck.setText("Flurst\u00fcck umbenennen");
        cboRenameFlurstueck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cboRenameFlurstueck.setFocusPainted(false);
        cboRenameFlurstueck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        cboSetFlurstueckHistoric.setText("Flurst\u00fcck historisch setzen");
        cboSetFlurstueckHistoric.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cboSetFlurstueckHistoric.setFocusPainted(false);
        cboSetFlurstueckHistoric.setMargin(new java.awt.Insets(0, 0, 0, 0));

        cboSplitFlurstueck.setText("Flurst\u00fcck teilen");
        cboSplitFlurstueck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cboSplitFlurstueck.setFocusPainted(false);
        cboSplitFlurstueck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        cboJoinFlurstueck.setText("Flurst\u00fcck zusammenlegen");
        cboJoinFlurstueck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cboJoinFlurstueck.setFocusPainted(false);
        cboJoinFlurstueck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        cboSplitJoinFlurstueck.setText("Flurst\u00fcck zusammenlegen/teilen");
        cboSplitJoinFlurstueck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cboSplitJoinFlurstueck.setFocusPainted(false);
        cboSplitJoinFlurstueck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        cboChangeKind.setText("Art des Flurst\u00fccks \u00e4ndern");
        cboChangeKind.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cboChangeKind.setFocusPainted(false);
        cboChangeKind.setMargin(new java.awt.Insets(0, 0, 0, 0));

        final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(
                0,
                372,
                Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(
                0,
                58,
                Short.MAX_VALUE));

        cboSetFlurstueckActive.setText("Flurst\u00fcck aktivieren");
        cboSetFlurstueckActive.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cboSetFlurstueckActive.setFocusPainted(false);
        cboSetFlurstueckActive.setMargin(new java.awt.Insets(0, 0, 0, 0));

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                        jPanel1,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE).addGroup(
                        layout.createSequentialGroup().addContainerGap().addGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                                cboCreateFlurstueck).addComponent(cboRenameFlurstueck).addComponent(
                                cboSetFlurstueckHistoric)).addGap(26, 26, 26)).addGroup(
                        layout.createSequentialGroup().addContainerGap().addComponent(cboSetFlurstueckActive)).addGroup(
                        layout.createSequentialGroup().addContainerGap().addGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                                cboSplitFlurstueck).addComponent(cboJoinFlurstueck).addComponent(
                                cboSplitJoinFlurstueck).addComponent(cboChangeKind)))).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addComponent(
                    jPanel1,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cboCreateFlurstueck)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                    cboRenameFlurstueck).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(
                                cboSetFlurstueckHistoric,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                14,
                                javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cboSetFlurstueckActive)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                    cboSplitFlurstueck).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboJoinFlurstueck).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cboSplitJoinFlurstueck)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                    cboChangeKind).addContainerGap(60, Short.MAX_VALUE)));
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void cboCreateFlurstueckActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cboCreateFlurstueckActionPerformed
// TODO add your handling code here:
    } //GEN-LAST:event_cboCreateFlurstueckActionPerformed
}
