/*
 * HistoricActionPanel.java
 *
 * Created on 10. September 2007, 10:35
 */

package de.cismet.lagis.wizard.panels;

import de.cismet.lagis.broker.EJBroker;
import de.cismet.lagis.validation.Validatable;
import de.cismet.lagis.validation.ValidationStateChangedListener;
import de.cismet.lagisEE.entity.locking.Sperre;
import java.util.Map;
import org.apache.log4j.Logger;
import org.netbeans.spi.wizard.WizardController;

/**
 *
 * @author  Sebastian Puhl
 */
public class HistoricActionPanel extends javax.swing.JPanel implements ValidationStateChangedListener {
    public static final String KEY_HISTORIC_CANDIDATE = "historicCandidate";
    private final Logger log = org.apache.log4j.Logger.getLogger(this.getClass());
    private WizardController wizardController;
    private Map wizardData;
    /** Creates new form HistoricActionPanel */
    public HistoricActionPanel(WizardController wizardController, Map wizardData) {
        log.debug("Historic Action Panel wird angelegt");
        initComponents();
        this.wizardController = wizardController;
        this.wizardData = wizardData;
        wizardController.setProblem("Bitte wählen Sie das Flurstück aus das historisch gesetzt werden soll");
        panHistoric.addValidationStateChangedListener(this);        
    }
    
     //TODO HISTORIC CHECK
     public void validationStateChanged(Object validatedObject) {
        if(panHistoric.getStatus() == Validatable.VALID){
            Sperre sperre = EJBroker.getInstance().isLocked(panHistoric.getCurrentFlurstueckSchluessel());
            if(sperre != null){                
                //TODO nicht ganz sichtbar
                wizardController.setProblem("Ausgewähltes Flurstück ist gesperrt von Benutzer: "+sperre.getBenutzerkonto());
                return;
            } else {                
                wizardData.put(KEY_HISTORIC_CANDIDATE,panHistoric.getCurrentFlurstueckSchluessel());
                wizardController.setProblem(null);
                wizardController.setForwardNavigationMode(wizardController.MODE_CAN_FINISH);
            }
        } else {
            wizardController.setProblem(panHistoric.getValidationMessage());
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panHistoric = new de.cismet.lagis.gui.panels.FlurstueckChooser();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jLabel1.setText("Flurst\u00fcck");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panHistoric, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panHistoric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private de.cismet.lagis.gui.panels.FlurstueckChooser panHistoric;
    // End of variables declaration//GEN-END:variables
    
}
