
/*
 * HistoryLegendPanel.java
 *
 * Created on 10.09.2009, 11:21:53
 */

package de.cismet.lagis.layout.widget;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * This panel displayes a Legend over the icons used within the History Module.
 *
 * @author mbrill
 */
public class HistoryLegendPanel extends javax.swing.JPanel {

    private ResourceBundle icon_bundle = ResourceBundle.getBundle("de/cismet/lagis/ressource/history/icon", new Locale("de", "DE"));

    /** Creates new form HistoryLegendPanel */
    public HistoryLegendPanel() {
        initComponents();

        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource(icon_bundle.getString("städtisch")));
        flurstueckIconLabel.setIcon(icon);
        icon = new ImageIcon(getClass().getResource(icon_bundle.getString("Abteilung IX")));
        abt9IconLabel.setIcon(icon);
        icon = new ImageIcon(getClass().getResource(icon_bundle.getString("städtisch_historic")));
        historicIconLabel.setIcon(icon);
        icon = new ImageIcon(getClass().getResource(icon_bundle.getString("icon_locked")));
        lockedIconLabel.setIcon(icon);
        icon = new ImageIcon(getClass().getResource(icon_bundle.getString("icon_dms")));
        dmsIconLabel.setIcon(icon);
        icon = new ImageIcon(getClass().getResource(icon_bundle.getString("icon_right")));
        rightIconLabel.setIcon(icon);
        icon = new ImageIcon(getClass().getResource(icon_bundle.getString("icon_load")));
        loadIconLabel.setIcon(icon);
        icon = new ImageIcon(getClass().getResource(icon_bundle.getString("icon_contracts")));
        contractIconLabel.setIcon(icon);
        icon = new ImageIcon(getClass().getResource(icon_bundle.getString("default")));
        unknownIconLabel.setIcon(icon);
        
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        flurstueckLabel = new javax.swing.JLabel();
        abt9Label = new javax.swing.JLabel();
        historicLabel = new javax.swing.JLabel();
        lockedLabel = new javax.swing.JLabel();
        rightLabel = new javax.swing.JLabel();
        loadLabel = new javax.swing.JLabel();
        contractsLabel = new javax.swing.JLabel();
        dmsLabel = new javax.swing.JLabel();
        flurstueckIconLabel = new javax.swing.JLabel();
        abt9IconLabel = new javax.swing.JLabel();
        historicIconLabel = new javax.swing.JLabel();
        lockedIconLabel = new javax.swing.JLabel();
        rightIconLabel = new javax.swing.JLabel();
        loadIconLabel = new javax.swing.JLabel();
        contractIconLabel = new javax.swing.JLabel();
        dmsIconLabel = new javax.swing.JLabel();
        unknownLabel = new javax.swing.JLabel();
        unknownIconLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        flurstueckLabel.setText("Flurstück");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(flurstueckLabel, gridBagConstraints);

        abt9Label.setText("Abteilung 9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(abt9Label, gridBagConstraints);

        historicLabel.setText("historisch");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(historicLabel, gridBagConstraints);

        lockedLabel.setText("gesperrt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(lockedLabel, gridBagConstraints);

        rightLabel.setText("Recht");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(rightLabel, gridBagConstraints);

        loadLabel.setText("Belastung");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(loadLabel, gridBagConstraints);

        contractsLabel.setText("Verträge");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(contractsLabel, gridBagConstraints);

        dmsLabel.setText("DMS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(dmsLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(flurstueckIconLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(abt9IconLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(historicIconLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(lockedIconLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(rightIconLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(loadIconLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(contractIconLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(dmsIconLabel, gridBagConstraints);

        unknownLabel.setText("unbekannt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(unknownLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(unknownIconLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abt9IconLabel;
    private javax.swing.JLabel abt9Label;
    private javax.swing.JLabel contractIconLabel;
    private javax.swing.JLabel contractsLabel;
    private javax.swing.JLabel dmsIconLabel;
    private javax.swing.JLabel dmsLabel;
    private javax.swing.JLabel flurstueckIconLabel;
    private javax.swing.JLabel flurstueckLabel;
    private javax.swing.JLabel historicIconLabel;
    private javax.swing.JLabel historicLabel;
    private javax.swing.JLabel loadIconLabel;
    private javax.swing.JLabel loadLabel;
    private javax.swing.JLabel lockedIconLabel;
    private javax.swing.JLabel lockedLabel;
    private javax.swing.JLabel rightIconLabel;
    private javax.swing.JLabel rightLabel;
    private javax.swing.JLabel unknownIconLabel;
    private javax.swing.JLabel unknownLabel;
    // End of variables declaration//GEN-END:variables

    public JLabel getAbt9IconLabel() {
        return abt9IconLabel;
    }

    public void setAbt9IconLabel(JLabel abt9IconLabel) {
        this.abt9IconLabel = abt9IconLabel;
    }

    public JLabel getAbt9Label() {
        return abt9Label;
    }

    public void setAbt9Label(JLabel abt9Label) {
        this.abt9Label = abt9Label;
    }

    public JLabel getContractIconLabel() {
        return contractIconLabel;
    }

    public void setContractIconLabel(JLabel contractIconLabel) {
        this.contractIconLabel = contractIconLabel;
    }

    public JLabel getContractsLabel() {
        return contractsLabel;
    }

    public void setContractsLabel(JLabel contractsLabel) {
        this.contractsLabel = contractsLabel;
    }

    public JLabel getDmsIconLabel() {
        return dmsIconLabel;
    }

    public void setDmsIconLabel(JLabel dmsIconLabel) {
        this.dmsIconLabel = dmsIconLabel;
    }

    public JLabel getDmsLabel() {
        return dmsLabel;
    }

    public void setDmsLabel(JLabel dmsLabel) {
        this.dmsLabel = dmsLabel;
    }

    public JLabel getFlurstueckIconLabel() {
        return flurstueckIconLabel;
    }

    public void setFlurstueckIconLabel(JLabel flurstueckIconLabel) {
        this.flurstueckIconLabel = flurstueckIconLabel;
    }

    public JLabel getHistoricIconLabel() {
        return historicIconLabel;
    }

    public void setHistoricIconLabel(JLabel historicIconLabel) {
        this.historicIconLabel = historicIconLabel;
    }

    public JLabel getHistoricLabel() {
        return historicLabel;
    }

    public void setHistoricLabel(JLabel historicLabel) {
        this.historicLabel = historicLabel;
    }

    public ResourceBundle getIcon_bundle() {
        return icon_bundle;
    }

    public void setIcon_bundle(ResourceBundle icon_bundle) {
        this.icon_bundle = icon_bundle;
    }

    public JLabel getLfurstueckLabel() {
        return flurstueckLabel;
    }

    public void setLfurstueckLabel(JLabel flurstueckLabel) {
        this.flurstueckLabel = flurstueckLabel;
    }

    public JLabel getLoadIconLabel() {
        return loadIconLabel;
    }

    public void setLoadIconLabel(JLabel loadIconLabel) {
        this.loadIconLabel = loadIconLabel;
    }

    public JLabel getLoadLabel() {
        return loadLabel;
    }

    public void setLoadLabel(JLabel loadLabel) {
        this.loadLabel = loadLabel;
    }

    public JLabel getLockedIconLabel() {
        return lockedIconLabel;
    }

    public void setLockedIconLabel(JLabel lockedIconLabel) {
        this.lockedIconLabel = lockedIconLabel;
    }

    public JLabel getLockedLabel() {
        return lockedLabel;
    }

    public void setLockedLabel(JLabel lockedLabel) {
        this.lockedLabel = lockedLabel;
    }

    public JLabel getRightIconLabel() {
        return rightIconLabel;
    }

    public void setRightIconLabel(JLabel rightIconLabel) {
        this.rightIconLabel = rightIconLabel;
    }

    public JLabel getRightLabel() {
        return rightLabel;
    }

    public void setRightLabel(JLabel rightLabel) {
        this.rightLabel = rightLabel;
    }

    public JLabel getUnknownIconLabel() {
        return unknownIconLabel;
    }

    public void setUnknownIconLabel(JLabel unknownIconLabel) {
        this.unknownIconLabel = unknownIconLabel;
    }

    public JLabel getUnknownLabel() {
        return unknownLabel;
    }

    public void setUnknownLabel(JLabel unknownLabel) {
        this.unknownLabel = unknownLabel;
    }

}
