/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.lagis.report.scriptlet;

import javafx.application.Platform;

import javafx.embed.swing.SwingFXUtils;

import javafx.scene.SnapshotParameters;
import javafx.scene.image.WritableImage;

import org.apache.commons.io.IOUtils;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.image.RenderedImage;

import java.io.File;

import javax.imageio.ImageIO;

import de.cismet.tools.gui.FXWebViewPanel;

/**
 * DOCUMENT ME!
 *
 * @author   thorsten
 * @version  $Revision$, $Date$
 */
public class NewJFrame extends javax.swing.JFrame {

    //~ Instance fields --------------------------------------------------------

    FXWebViewPanel myWeb = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panMain;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form NewJFrame.
     */
    public NewJFrame() {
        initComponents();
        ((CardLayout)panMain.getLayout()).show(panMain, "progress");
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(
            jButton1,
            org.openide.util.NbBundle.getMessage(NewJFrame.class, "NewJFrame.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

        org.openide.awt.Mnemonics.setLocalizedText(
            jButton2,
            org.openide.util.NbBundle.getMessage(NewJFrame.class, "NewJFrame.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

        panMain.setLayout(new java.awt.CardLayout());

        jScrollPane1.setName("web"); // NOI18N
        panMain.add(jScrollPane1, "web");

        jProgressBar1.setIndeterminate(true);

        final javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel2Layout.createSequentialGroup().addContainerGap(54, Short.MAX_VALUE).addComponent(
                    jProgressBar1,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE).addGap(47, 47, 47)));
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                jPanel2Layout.createSequentialGroup().addGap(73, 73, 73).addComponent(
                    jProgressBar1,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(89, Short.MAX_VALUE)));

        panMain.add(jPanel2, "progress");

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addGroup(
                                    layout.createSequentialGroup().addComponent(jButton1).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE).addComponent(jButton2)).addComponent(
                                    panMain,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    247,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(111, 111, 111)));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton1)
                                .addComponent(jButton2)).addGap(25, 25, 25).addComponent(
                    panMain,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    182,
                    javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(38, Short.MAX_VALUE)));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton1ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            final String s = IOUtils.toString(this.getClass().getResourceAsStream("dagreReportingTemplate.html"));
            new Thread() {

                    @Override
                    public void run() {
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex) {
                        }

                        System.out.println("init FXWexxxbViewPanel");
                        myWeb = new FXWebViewPanel();
                        System.out.println("FXWebViewPanel inited");

                        EventQueue.invokeLater(new Runnable() {

                                @Override
                                public void run() {
                                    jScrollPane1.getViewport().add(myWeb);
                                    myWeb.setVisible(true);
//                                    final WebView webView = myWeb.getWebView();
//                                    webView.setMaxHeight(1000d);
//                                    webView.setMinHeight(1000d);
//                                    webView.setMaxWidth(1000d);
//                                    webView.setMinWidth(1000d);
//                                    webView.setZoom(0.4);

//                                    myWeb.setMinimumSize(new Dimension(4010, 4010));
//                                    myWeb.setMaximumSize(new Dimension(4010, 4010));
//                                    myWeb.setPreferredSize(new Dimension(4010, 4010));
                                    myWeb.setSize(new Dimension(4010, 4010));
                                    Platform.runLater(new Runnable() {

                                            @Override
                                            public void run() {
                                                try {
                                                    myWeb.loadContent(s);
//                                        Thread.sleep(1000);
//                                        final WritableImage snapshot = myWeb.getWebView()
//                                                .snapshot(new SnapshotParameters(), null);
//                                        final RenderedImage renderedImage = SwingFXUtils.fromFXImage(
//                                                snapshot,
//                                                null);
//
//                                        final File captureFile = new File("/Users/thorsten/tmp/x/cap.png");
//                                        ImageIO.write(renderedImage, "png", captureFile);
                                                } catch (Throwable t) {
                                                    t.printStackTrace();
                                                }
                                            }
                                        });
                                }
                            });
                    }
                }.start();
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    } //GEN-LAST:event_jButton1ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton2ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton2ActionPerformed
        // TOD Platform.runLater(new Runnable() {
        Platform.runLater(new Runnable() {

                @Override
                public void run() {
                    try {
                        final WritableImage snapshot = myWeb.getWebView().snapshot(new SnapshotParameters(), null);
                        final RenderedImage renderedImage = SwingFXUtils.fromFXImage(
                                snapshot,
                                null);

                        final File captureFile = new File("/Users/thorsten/tmp/x/cap.png");
                        ImageIO.write(renderedImage, "png", captureFile);
                    } catch (Throwable t) {
                        t.printStackTrace();
                    }
                }
            });
    } //GEN-LAST:event_jButton2ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  args  the command line arguments
     */
    public static void main(final String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    new NewJFrame().setVisible(true);
                }
            });
    }
}
