/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * PlanPanel.java
 *
 * Created on 17. Mai 2007, 15:11
 */
package de.cismet.lagis.gui.panels;

import org.jdesktop.swingx.JXTable;
import org.jdesktop.swingx.autocomplete.ComboBoxCellEditor;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JDialog;

import de.cismet.cids.custom.beans.verdis_grundis.BebauungCustomBean;
import de.cismet.cids.custom.beans.verdis_grundis.FlaechennutzungCustomBean;

import de.cismet.lagis.broker.EJBroker;

import de.cismet.lagis.models.PlanTableModel;

import de.cismet.lagisEE.interfaces.Plan;

/**
 * DOCUMENT ME!
 *
 * @author   Puhl
 * @version  $Revision$, $Date$
 */
public class PlanPanel extends javax.swing.JPanel implements MouseListener {

    //~ Instance fields --------------------------------------------------------

    private PlanTableModel tableModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntok;
    private javax.swing.JButton btnAddPlan;
    private javax.swing.JButton btnRemovePlan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlKostenControls1;
    private javax.swing.JTable tblPlan;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form PlanPanel.
     *
     * @param  tableModel  DOCUMENT ME!
     */
    public PlanPanel(final PlanTableModel tableModel) {
        initComponents();
        this.tableModel = tableModel;
        tblPlan.setModel(tableModel);
        JComboBox cboPlaene;
        if (tableModel.isFnpModel()) {
            cboPlaene = new JComboBox(new Vector<Plan>(EJBroker.getInstance().getAllFlaechennutzungen()));
            // System.out.println("istFlaechennutzung");
        } else {
            cboPlaene = new JComboBox(new Vector<Plan>(EJBroker.getInstance().getAllBebauungen()));
            // System.out.println("istbebauung");
        }
        cboPlaene.setEditable(true);
        tblPlan.setDefaultEditor(Plan.class, new ComboBoxCellEditor(cboPlaene));
        if (tblPlan.getSelectedRow() != -1) {
            btnRemovePlan.setEnabled(true);
        } else {
            btnRemovePlan.setEnabled(false);
        }
        tblPlan.addMouseListener(this);
    }

    //~ Methods ----------------------------------------------------------------

    @Override
    public void mouseReleased(final MouseEvent e) {
    }

    @Override
    public void mousePressed(final MouseEvent e) {
    }

    @Override
    public void mouseExited(final MouseEvent e) {
    }

    @Override
    public void mouseEntered(final MouseEvent e) {
    }

    @Override
    public void mouseClicked(final MouseEvent e) {
        final Object source = e.getSource();
        if (source instanceof JXTable) {
            if (((JXTable)source).getSelectedRow() != -1) {
                btnRemovePlan.setEnabled(true);
            } else {
                btnRemovePlan.setEnabled(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlKostenControls1 = new javax.swing.JPanel();
        btnAddPlan = new javax.swing.JButton();
        btnRemovePlan = new javax.swing.JButton();
        bntok = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlan = new JXTable();

        btnAddPlan.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/de/cismet/lagis/ressource/icons/buttons/add.png")));
        btnAddPlan.setBorder(null);
        btnAddPlan.setOpaque(false);
        btnAddPlan.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnAddPlanActionPerformed(evt);
                }
            });

        btnRemovePlan.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/de/cismet/lagis/ressource/icons/buttons/remove.png")));
        btnRemovePlan.setBorder(null);
        btnRemovePlan.setOpaque(false);
        btnRemovePlan.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnRemovePlanActionPerformed(evt);
                }
            });

        bntok.setText("OK");
        bntok.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    bntokActionPerformed(evt);
                }
            });

        final org.jdesktop.layout.GroupLayout pnlKostenControls1Layout = new org.jdesktop.layout.GroupLayout(
                pnlKostenControls1);
        pnlKostenControls1.setLayout(pnlKostenControls1Layout);
        pnlKostenControls1Layout.setHorizontalGroup(
            pnlKostenControls1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                pnlKostenControls1Layout.createSequentialGroup().add(
                    btnAddPlan,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    75,
                    Short.MAX_VALUE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                    btnRemovePlan,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    74,
                    Short.MAX_VALUE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                    bntok,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    75,
                    Short.MAX_VALUE).addContainerGap()));
        pnlKostenControls1Layout.setVerticalGroup(
            pnlKostenControls1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                pnlKostenControls1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false).add(
                    btnRemovePlan,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    27,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(
                    btnAddPlan,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    27,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(
                    bntok,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    27,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));

        pnlKostenControls1Layout.linkSize(
            new java.awt.Component[] { btnAddPlan, btnRemovePlan },
            org.jdesktop.layout.GroupLayout.VERTICAL);

        tblPlan.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null },
                    { null, null, null, null }
                },
                new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
        jScrollPane2.setViewportView(tblPlan);

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        pnlKostenControls1,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(
                        jScrollPane2,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        477,
                        Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().add(31, 31, 31).add(
                    pnlKostenControls1,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                    org.jdesktop.layout.LayoutStyle.RELATED).add(
                    jScrollPane2,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    374,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)));
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void bntokActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_bntokActionPerformed
        ((JDialog)this.getRootPane().getParent()).dispose();
    }                                                                         //GEN-LAST:event_bntokActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnRemovePlanActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnRemovePlanActionPerformed
        final int currentRow = tblPlan.getSelectedRow();
        if (currentRow != -1) {
            // VerwaltungsTableModel currentModel = (VerwaltungsTableModel)tNutzung.getModel();
            tableModel.removePlan(((JXTable)tblPlan).getFilters().convertRowIndexToModel(
                    ((JXTable)tblPlan).getFilters().convertRowIndexToModel(currentRow)));
            tableModel.fireTableDataChanged();
        }
    } //GEN-LAST:event_btnRemovePlanActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnAddPlanActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnAddPlanActionPerformed
        if (tableModel.isFnpModel()) {
            tableModel.addPlan(new FlaechennutzungCustomBean());
        } else {
            tableModel.addPlan(new BebauungCustomBean());
        }
        tableModel.fireTableDataChanged();
    }                                                                              //GEN-LAST:event_btnAddPlanActionPerformed
}
