/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * RessortPanel.java
 *
 * Created on 16. März 2007, 11:59
 */
package de.cismet.lagis.gui.panels;

import javax.swing.Icon;

import de.cismet.cids.custom.beans.lagis.FlurstueckCustomBean;

import de.cismet.lagis.broker.LagisBroker;

import de.cismet.lagis.interfaces.FlurstueckChangeListener;

import de.cismet.lagis.widget.AbstractWidget;

/**
 * DOCUMENT ME!
 *
 * @author   Puhl
 * @version  $Revision$, $Date$
 */
//TODO Delete
public class RessortPanel extends AbstractWidget implements FlurstueckChangeListener {

    //~ Static fields/initializers ---------------------------------------------

    private static final String WIDGET_NAME = "Ressort Panel";

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form RessortPanel.
     */
    public RessortPanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    @Override
    public void flurstueckChanged(final FlurstueckCustomBean newFlurstueck) {
        LagisBroker.getInstance().flurstueckChangeFinished(this);
    }

    @Override
    public void setComponentEditable(final boolean isEditable) {
    }

    @Override
    public synchronized void clearComponent() {
    }

    @Override
    public void refresh(final Object refreshObject) {
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 176, Short.MAX_VALUE));
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public String getWidgetName() {
        return WIDGET_NAME;
    }

    @Override
    public Icon getWidgetIcon() {
        return null;
    }
}
