/*
 * RessortPanel.java
 *
 * Created on 16. März 2007, 11:59
 */

package de.cismet.lagis.gui.panels;

import de.cismet.lagis.broker.LagisBroker;
import de.cismet.lagis.interfaces.FlurstueckChangeListener;
import de.cismet.lagis.interfaces.Widget;
import de.cismet.lagis.widget.AbstractWidget;
import de.cismet.lagisEE.entity.core.Flurstueck;
import javax.swing.Icon;


/**
 *
 * @author  Puhl
 */
//TODO Delete
public class RessortPanel extends AbstractWidget implements FlurstueckChangeListener {
    private static final String WIDGET_NAME = "Ressort Panel";
    /** Creates new form RessortPanel */
    public RessortPanel() {
        initComponents();
    }

    public void flurstueckChanged(Flurstueck newFlurstueck) {
        LagisBroker.getInstance().flurstueckChangeFinished(this);
    }

    public void setComponentEditable(boolean isEditable) {
    }

    public synchronized void clearComponent() {
    }

            
    
    public void refresh(Object refreshObject) {
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 176, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
   
    public String getWidgetName() {
        return WIDGET_NAME;
    }

    

    public Icon getWidgetIcon() {
        return null;
    }        
}
