/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.lagis.gui.panels;

import java.util.Collection;

import javax.swing.JSeparator;

import de.cismet.cids.custom.beans.lagis.FlurstueckCustomBean;
import de.cismet.cids.custom.beans.lagis.VerwaltungsbereicheEintragCustomBean;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class VerwaltungsbereicheHistoriePanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panBottom;
    private javax.swing.JPanel panHistorie;
    private javax.swing.JPanel panItems;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form VerwaltungsHistoriePanel.
     */
    public VerwaltungsbereicheHistoriePanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @param  fsBean  DOCUMENT ME!
     */
    public void setFlurstueck(final FlurstueckCustomBean fsBean) {
        final Collection<VerwaltungsbereicheEintragCustomBean> eintraege = fsBean.getVerwaltungsbereicheHistorie();
        int gridY = 0;
        for (final VerwaltungsbereicheEintragCustomBean eintrag : eintraege) {
            java.awt.GridBagConstraints gridBagConstraints;
            if (gridY > 0) {
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = gridY++;
                panItems.add(new JSeparator(JSeparator.HORIZONTAL), gridBagConstraints);
            }

            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints.weightx = 1.0;
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = gridY++;
            panItems.add(new VerwaltungsbereicheHistorieEintragPanel(eintrag), gridBagConstraints);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panHistorie = new javax.swing.JPanel();
        panItems = new javax.swing.JPanel();
        panBottom = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        panHistorie.setLayout(new java.awt.GridBagLayout());

        panItems.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panHistorie.add(panItems, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(panHistorie, gridBagConstraints);

        panBottom.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(panBottom, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents
}
